service: ports

provider:
  name: aws
  runtime: nodejs4.3

defaults:
  stage: prod
  region: eu-west-1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  ports:
    handler: ports/ports.hello
    events:
      - http:
          path: ports
          method: get

  port:
    handler: ports/port.hello
    events:
      - http:
          path: ports/{id}
          method: get


# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    newResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: newBucket
